title: Pablo Herrero Ortiz | Digital Portfolio
author: Pablo Herrero Ortiz

remote_theme: "Mandorlino/PortfolYOU"
baseurl: "" 
url: "https://pabloherrero.github.io" 

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
