title: Pablo Herrero Ortiz | Digital Portfolio
author: Pablo Herrero Ortiz
email: pablo.herrort@gmail.com
timezone: Europe/Amsterdam
description: "Digital Portfolio of Pablo Herrero Ortiz"

remote_theme: "yousinix/portfolYOU"

baseurl: "" 
url: "https://pabloherrero.github.io" 

markdown: kramdown
permalink: /:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor/
  - README.md
  - LICENSE
